# brew "git"
# brew "gitmoji"  # nodeの最新版を勝手に入れてくるので、一旦使用中止
# brew "git-secrets"
# brew "heroku"
# brew "jq"
# brew "libyaml"
# brew "nightlight"
# brew "rbenv"
# brew "rename"
# brew "ricty"
# brew "rsync"
# brew "ruby-build"
# brew "shellcheck"
# brew "tflint"
# brew "tfsec"
brew "tree"
brew "volta"
# brew "watch"
# brew "watchman"
brew "wget"
